CREATE TABLE Publisher (
	PUBLISHER_ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(255)
	);
	
CREATE TABLE Category (
	CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(255)
	);
	
CREATE TABLE Author (
	AUTHOR_ID INT IDENTITY(1,1) PRIMARY KEY,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	DATE_OF_BIRTH DATE,
	DESCRIPTION TEXT
	);
	
CREATE TABLE Book (
	BOOK_ID INT IDENTITY(1,1) PRIMARY KEY,
	TITLE VARCHAR(255) NOT NULL,
	DESCRIPTION TEXT,
	QUANTITY INT NOT NULL,
	PUBLISHMENT_DATE DATE NOT NULL,
	ISBN VARCHAR(255) NOT NULL,
	PUBLISHER_ID INT NOT NULL,
	EDITION VARCHAR(255) NOT NULL,
	CONSTRAINT FK_BookPublisher FOREIGN KEY (PUBLISHER_ID)
    REFERENCES Publisher(PUBLISHER_ID)
    );
	
CREATE TABLE Person (
	PERSON_ID INT IDENTITY(1,1) PRIMARY KEY,
	EMAIL VARCHAR(255) NOT NULL,
	LOGIN VARCHAR(255) NOT NULL,
	PASSWORD TEXT
	);
	
CREATE TABLE Address (
	ADDRESS_ID INT IDENTITY(1,1) PRIMARY KEY,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	STREET VARCHAR(255) NOT NULL,
	CITY VARCHAR(255) NOT NULL,
	ZIP_CODE VARCHAR(255) NOT NULL,
	COUNTRY VARCHAR(255) NOT NULL,
	TEL_NUMBER VARCHAR(255) NOT NULL,
	PERSON_ID INT NOT NULL,
	CONSTRAINT FK_AddressPerson FOREIGN KEY (PERSON_ID)
    REFERENCES Person(PERSON_ID)
	);
	
CREATE TABLE Employee (
	EMPLOYEE_ID INT IDENTITY(1,1) PRIMARY KEY,
	PERSON_ID INT NOT NULL,
	ACTIVE BIT NOT NULL,
	CONSTRAINT FK_EmployeePerson FOREIGN KEY (PERSON_ID)
    REFERENCES Person(PERSON_ID)
	);
	
CREATE TABLE Opinion (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	DESCRIPTION TEXT,
	RATE INT NOT NULL,
	BOOK_ID INT NOT NULL,
	PERSON_ID INT NOT NULL,
	CONSTRAINT FK_OpinionBook FOREIGN KEY (BOOK_ID)
    REFERENCES Book(BOOK_ID),
	CONSTRAINT FK_OpinionPerson FOREIGN KEY (PERSON_ID)
    REFERENCES Person(PERSON_ID)
    );
	
CREATE TABLE Borrow (
	BORROW_ID INT IDENTITY(1,1) PRIMARY KEY,
	DATE_OF_BORROW DATETIME NOT NULL DEFAULT GETDATE(),
	DATE_OF_RETURN DATETIME,
	BOOK_ID INT NOT NULL,
	PERSON_ID INT NOT NULL,
	EMPLOYEE_ID INT NOT NULL,
	CONSTRAINT FK_BorrowBook FOREIGN KEY (BOOK_ID)
    REFERENCES Book(BOOK_ID),
	CONSTRAINT FK_BorrowPerson FOREIGN KEY (PERSON_ID)
    REFERENCES Person(PERSON_ID),
	CONSTRAINT FK_BorrowEmployee FOREIGN KEY (EMPLOYEE_ID)
    REFERENCES Employee(EMPLOYEE_ID)
	);

CREATE TABLE BookAuthorRelation (
	BOOK_ID INT NOT NULL,
	AUTHOR_ID INT NOT NULL,
	FOREIGN KEY (BOOK_ID) REFERENCES Book(BOOK_ID),
	FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID),
	UNIQUE (BOOK_ID, AUTHOR_ID)
	);
	
CREATE TABLE BookCategoryRelation (
	BOOK_ID INT NOT NULL,
	CATEGORY_ID INT NOT NULL
	FOREIGN KEY (BOOK_ID) REFERENCES Book(BOOK_ID),
	FOREIGN KEY (CATEGORY_ID) REFERENCES Category(CATEGORY_ID),
	UNIQUE (BOOK_ID, CATEGORY_ID)
	);