INSERT INTO Category(NAME) VALUES ('Textbook');
INSERT INTO Category(NAME) VALUES ('Fanfiction');
INSERT INTO Category(NAME) VALUES ('Fiction in verse');
INSERT INTO Category(NAME) VALUES ('Textbook');
INSERT INTO Category(NAME) VALUES ('Comic/Graphic Novel');
INSERT INTO Category(NAME) VALUES ('Mythopoeia');
INSERT INTO Category(NAME) VALUES ('Mythology');
INSERT INTO Category(NAME) VALUES ('Horror');
INSERT INTO Category(NAME) VALUES ('Horror');
INSERT INTO Category(NAME) VALUES ('Classic');
INSERT INTO Category(NAME) VALUES ('Realistic fiction');
INSERT INTO Category(NAME) VALUES ('Historical fiction');
INSERT INTO Category(NAME) VALUES ('Fiction narrative');
INSERT INTO Category(NAME) VALUES ('Fanfiction');
INSERT INTO Category(NAME) VALUES ('Mythology');
INSERT INTO Category(NAME) VALUES ('Folklore');
INSERT INTO Category(NAME) VALUES ('Essay');
INSERT INTO Category(NAME) VALUES ('Narrative nonfiction');
INSERT INTO Category(NAME) VALUES ('Metafiction');
INSERT INTO Category(NAME) VALUES ('Horror');
INSERT INTO Category(NAME) VALUES ('Realistic fiction');
INSERT INTO Category(NAME) VALUES ('Speech');
INSERT INTO Category(NAME) VALUES ('Mythopoeia');
INSERT INTO Category(NAME) VALUES ('Speech');
INSERT INTO Category(NAME) VALUES ('Historical fiction');
