INSERT INTO Publisher(NAME) VALUES ('Parragon');
INSERT INTO Publisher(NAME) VALUES ('Chatto and Windus');
INSERT INTO Publisher(NAME) VALUES ('Naiad Press');
INSERT INTO Publisher(NAME) VALUES ('Carnegie Mellon University Press');
INSERT INTO Publisher(NAME) VALUES ('Happy House');
INSERT INTO Publisher(NAME) VALUES ('Peace Hill Press');
INSERT INTO Publisher(NAME) VALUES ('Gay Men''s Press');
INSERT INTO Publisher(NAME) VALUES ('Firebrand Books');
INSERT INTO Publisher(NAME) VALUES ('Brill');
INSERT INTO Publisher(NAME) VALUES ('Left Book Club');
INSERT INTO Publisher(NAME) VALUES ('Harper & Row');
INSERT INTO Publisher(NAME) VALUES ('Canongate Books');
INSERT INTO Publisher(NAME) VALUES ('Tammi');
INSERT INTO Publisher(NAME) VALUES ('T & T Clark');
INSERT INTO Publisher(NAME) VALUES ('Taunton Press');
INSERT INTO Publisher(NAME) VALUES ('NavPress');
INSERT INTO Publisher(NAME) VALUES ('Lion Hudson');
INSERT INTO Publisher(NAME) VALUES ('Hawthorne Books');
INSERT INTO Publisher(NAME) VALUES ('Ladybird Books');
INSERT INTO Publisher(NAME) VALUES ('Mainstream Publishing');
